services:
  - type: web
    name: football-registration
    runtime: python
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8001
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
